# Generated by Django 4.2.6 on 2023-11-11 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='почта/логин')),
                ('password', models.CharField(max_length=60, unique=True, verbose_name='пароль')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('is_staff', models.BooleanField(default=False)),
                ('subscription', models.BooleanField(default=False, verbose_name='подписка')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('subscription_level', models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PageRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='ссылка')),
                ('duration_minutes', models.IntegerField(verbose_name='длительность в минутах')),
                ('shift', models.IntegerField(verbose_name='сдвиг')),
                ('content_type', models.CharField(choices=[('txt', 'Txt'), ('json', 'Json')], max_length=10)),
                ('send_email', models.BooleanField(default=False)),
                ('id_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='id')),
                ('class_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='DataPageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000, verbose_name='данные')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
