# Generated by Django 4.2.6 on 2023-11-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castomuser',
            name='free_subscription_is_use',
            field=models.BooleanField(default=False, verbose_name='бесплатная подписка'),
        ),
        migrations.AddField(
            model_name='datapagerequest',
            name='content_type',
            field=models.CharField(default='', max_length=10, verbose_name='тип контента'),
        ),
        migrations.AlterField(
            model_name='castomuser',
            name='subscription_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datapagerequest',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='pagerequests',
            name='content_type',
            field=models.CharField(choices=[('txt', 'Txt'), ('json', 'Json')], max_length=10, verbose_name='тип контента'),
        ),
    ]
