# Generated by Django 4.2.6 on 2023-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='название')),
                ('file', models.FileField(null=True, upload_to='result_data/', verbose_name='данные')),
                ('content_type', models.CharField(choices=[('json', 'JSON'), ('txt', 'TEXT DOCUMENT')], max_length=20, verbose_name='вид')),
            ],
        ),
    ]
