# Generated by Django 4.2.6 on 2023-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jsonelement_textelement_delete_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonelement',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='textelement',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
