# Generated by Django 4.2.6 on 2023-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jsonelement_date_create_textelement_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('file', models.FileField(null=True, upload_to='result_data/', verbose_name='данные')),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JsonElement',
        ),
        migrations.DeleteModel(
            name='TextElement',
        ),
    ]
