# Generated by Django 4.2.6 on 2023-12-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='уровень')),
                ('price', models.FloatField(verbose_name='стоимость')),
                ('min_shift', models.IntegerField(verbose_name='минимальная задержка в секундах')),
                ('max_shift', models.IntegerField(verbose_name='максимальная задержка в секундах')),
                ('maximum_request_duration', models.IntegerField(verbose_name='максимальная длительность запроса')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
